<h3> 09 - 21 </h3>

In [ ]:
num = 839
count = 0
while (num > 0):
    num = num // 10
    count += 1
print("Total digits are: ", count)

In [ ]:
list = ['Anna', 'Mary', 'John', 'Joseph']
for name in list:
    print("Happy birthday {}".format(name))

In [ ]:
# range(start, stop, step)

lists = [[0,1,3], [2,3]]

for i in range(len(lists)):
    x = len(lists[i])
    for j in range(0, x):
        print (lists[i][j], end=" ")
    print()

In [ ]:
list = [[0,1,2,3,4,5], [1,2,3,4,5,6,7]]
print(len(list[0]))

In [ ]:
squares = [element ** 2 for element in range(10)]
print(squares)
new_counts = [number + 10 for number in squares]
print(new_counts)

<h3> 09 - 23 </h3>

In [ ]:
x = (i for i in range(10))
print(x)

In [ ]:
list1 = [1,2,3,4]
list2 = ['a','b','c','d']
list3 = []
zipped_lists = zip(list1, list2, list3)
for item1, item2, item3 in zipped_lists:
    print (item1, item2, item3)

In [ ]:
x = [x,y,z]
for index, element in enumerate(x):
    print (index, element)

<h3> 09 - 25 </h3>

In [ ]:
for i in range(1,5):
    for j in range(i):
        print(i, end =' ')
    print()

In [ ]:
n = eval(input('Enter a number from 2 to 10: '))
for i in range (n):
    for j in range(i):
        print('*', end =' ')
    print(' ')
for i in range (n,0,-1):
    for j in range(i):
        print('*', end =' ')
    print(' ')

<h3> 09 - 28 </h3>

In [ ]:
from turtle import *

forward(100)
left(120)
forward(100)
left(120)
forward(100)
left(120)

done()

In [ ]:
from turtle import *

forward(100)
left(90)
forward(100)
left(90)
forward(100)
left(90)
forward(100)
left(90)

done()

In [ ]:
from turtle import *

for i in range(4):
    forward(100)
    left(90)
    
done()

In [ ]:
from turtle import *

sides = eval(input("Enter the number of sides on your polygon: "))
degrees = 360 / sides

for side in range(sides):
    forward(100)
    left(degrees)
    
done()

In [ ]:
from turtle import *

number_polygons = eval(input("Enter the number of polygons to be drawn: "))
sides = eval(input("Enter the number of sides on your polygon: "))
degrees = 360 / sides

for polygon in range(number_polygons):
    for side in range(sides):
        forward(50)
        left(degrees)
    penup()
    forward(70)
    pendown()
penup()
backward(70*number_polygons)
pendown()
    
done()

In [ ]:
from turtle import *

number_rows = eval(input("Enter the number of rows to be drawn: "))
number_polygons = eval(input("Enter the number of polygons in each row: "))
sides = eval(input("Enter the number of sides on your polygon: "))
degrees = 360 / sides

for rows in range(number_rows):
    for polygon in range(number_polygons):
        for side in range(sides):
            forward(50)
            left(degrees)
        penup()
        forward(70)
        pendown()
    penup()
    backward(70*number_polygons)
    right(90)
    forward(70)
    left(90)
    pendown()
done()

<h3>09-30</h3

In [ ]:
x = 5
if x > 5:
    print("How did this happen?!")
if x == 5 :
    print("Working as intended.")

In [ ]:
x = 6
if x < 5:
    print("How did this happen?!")
else:
    print("Correct.")

In [ ]:
x = [51, 65, 56, 19, 11, 49, 81, 59, 45, 73]
max_val = 0

for element in x:
    if max_val < element:
        max_val = element

print("The maximum element is: {}".format(max_val))

In [ ]:
student_grades = {
    'Jen': 82,
    'Shannon': 75,
    'Natasha': 94,
    'Benjamin': 48,  
}
for student, grade in student_grades.items():
    if grade >= 90:
        letter = "A"
    elif grade >= 80:
        letter = "B"
    elif grade >= 70:
        letter = "C"
    elif grade >= 60:
        letter = "D"
    else:
        letter = "F"
    print(student, letter)

<h3>10 - 02</h3>

<b>and</b>: all conditions are true <br>
<b>or</b>: one or more condition to be true

In [ ]:
x = [51, 65, 56, 19, 11, 49, 81, 59, 45, 73]
max_val = 81
second_largest = 0
for number in x:
    if second_largest < max_val and number < max_val:
        second_largest = number
print("The second largest number is: {}" .format(second_largest))

In [ ]:
x = [51, 65, 56, 19, 11, 49, 81, 59, 45, 73]
max_val = 81
second_largest = 0
for number in x:
    if second_largest < max_val:
        if number < max_val:
            second_largest = number
print("The second largest number is: {}" .format(second_largest))

<b>not</b>: is it not there? <br>
<b>in</b>: is it there?

In [ ]:
list_of_numbers = [i for i in range(10)]
lucky_number = eval(input("Enter your lucky number: "))
if lucky_number not in list_of_numbers:
    print("Boo! Lucky number not in the list!")
if lucky_number in list_of_numbers:
    print("You're in luck! Your number is in!")
print(list_of_numbers)

In [ ]:
noh = 25
noa = eval(input("Enter the number of classes attended: "))
percentage = noa/noh
print("Studet atttended {}% percent of classes" .format(percentage*100))
if percentage > 0.65:
    print("May take final exam.")
else: 
    print("Not allowed in final exam.")

In [ ]:
noh = 25
noa = eval(input("Enter the number of classes attended: "))
medicaldoc = eval(input("Medical documentation? (1 = Yes / 0 = No)"))
percentage = noa/noh
print("Studet atttended {}% percent of classes" .format(percentage*100))
if percentage > 0.65:
    print("May take final exam.")
elif medicaldoc == 1:
    print("May take final exam, because of medical document.")
else:
    print("Not allowed in final exam.")   

<h3>10 - 05</h3>

TypeError: trying to use a variable for a different function that it is intended
KeyError: 
IndexError: trying to index a number beyond range
NameError: when a variable is used before being created/assigned

"try" = holds the part of the code that might produce an exception (error)
"except" = what will happen if there is an exception (error)

In [ ]:
try:
    print(variable_that_doesnt_exist)
except:
    print("An error ocurred!")

print("Am I getting to this point?")

In [3]:
answer = input("Enter your answer (y/n): ")

try:
    if answer == 'y'or answer == 'Y':
        print("The answer is yes!")
    elif answer == 'n'or answer == 'N':
        print("The answer is no.")
    else:
#         raise SyntaxError("Answer doesn't suffice.")
        raise Exception
except:
    print("Wrong answer")

Enter your answer (y/n):  w


Wrong answer


In [ ]:
def divide(x,y):
    result = x/y
    return result
print(divide(2,3))

In [ ]:
def divide_safe(x,y):
    quotient = 0
    try:
        quotient = x/y
    except ZeroDivisionError:
            print("You tried to divide by zero. Why would you do that?")
    return quotient

print(divide_safe(2,0))

In [ ]:
import random
num = random.randint(0,1)

try:
    #code that might generate error
    pass
except NameError:
    print("Caught a NameError!")
except ValueError:
    print("Nope, it was actually a ValueError.")

In [ ]:
import random
num = random.randint(0,1)

try:
    #code that might generate error
    pass
except (NameError, ValueError):
    print("You got an error. Does not specify which.")

In [ ]:
import random
num = random.randint(0,1)

try:
    if num == 1:
        raise NameError("This happens when you use a variable you haven't defined")
    else:
        raise ValueError("This happens if you try to multiply a string.")
except NameError:
    print("Caught a NameError!")
except ValueError:
    print("Nope, it was actually a ValueError.")

In [ ]:
import random
num = random.randint(0,1)

try:
    if num == 1:
        raise NameError("This happens when you use a variable you haven't defined")
    else:
        raise ValueError("This happens if you try to multiply a string.")
except (NameError, ValueError):
    print("You got an error. Does not specify which.")

In [ ]:
import random
num = random.randint(0,1)

try:
    if num == 1:
        raise NameError("This happens when you use a variable you haven't defined")
    else:
        raise ValueError("This happens if you try to multiply a string.")
except:
    print("You got an error.")

In [ ]:
import random
num = random.randint(0,1)

try:
    if num == 1:
        raise NameError("This happens when you use a variable you haven't defined")
except:
    print("You got an error.")
else:
    print("Yay, lucky number!")
print(num)

In [ ]:
import random
num = random.randint(0,1)

try:
    if num == 1:
        raise NameError("This happens when you use a variable you haven't defined")
except:
    print("You got an error.")
else:
    print("Yay, lucky number!")
finally:
    print("I get printed all the time.")
print(num)

<h3>10-07</h3>

In [2]:
def function_name(argument1, argument2):
    print("The body of the function uses {} and {} to perfor a computation".format(argument1, argument2))

function_name("arguments", "inputs")

The body of the function uses arguments and inputs to perfor a computation


In [7]:
def another_function(user_range, steps = 1):
    print("This function prints a pattern the number of times and stpe size defined by the user")
    for i in range(0, user_range, steps):
        print("*" * i)

answer1 = eval(input("Enter the number of times the loop should be printed:"))
answer2 = eval(input("Enter the size of the steps between the loops - Enter 0 for default: "))

if answer2 == 0:
    another_function(answer1)
else:
    another_function(answer1, answer2)

Enter the number of times the loop should be printed: 15
Enter the size of the steps between the loops - Enter 0 for default:  0


This function prints a pattern the number of times and stpe size defined by the user

*
**
***
****
*****
******
*******
********
*********
**********
***********
************
*************
**************


In [2]:
def calculator(number1, number2, operation = '+'):
    if operation == '+':
        total = number1 + number2
    elif operation == '-':
        total = number1 - number2
    elif operation == '*':
        total = number1 * number2
    elif operation == '/':
        total = number1 / number2
    else:
        print("Invalid operation.")
    return total

# number1, number2 = eval(input("Enter the two numbers to be computed, separated by comma: "))
# operation = input("What operation should be performed? \n + for addition; - for subtraction; * for multiplication; / for division:")

# print("Your result is: {}".format(calculator(number1, number2, operation)))

print(calculator(2,3))
print(calculator(2,3,'-'))
print(calculator(2,3,'*'))
print(calculator(2,3,'/'))

5
-1
6
0.6666666666666666


In [13]:
# Patrick's solution

def calc(operation, par1, par2 ):
    ops = ['+', '-', '*', '**', '/', '//', '%']
    operation = str(operation)
    if operation not in ops:
        operation = operation.lower()
    if operation == '+' or operation == 'add':
        return par1 + par2
    elif operation == '-' or operation == 'sub':
        return par1 - par2
    elif operation == '*' or operation == 'mul':
        return par1 * par2
    elif operation == '**' or operation == 'pow':
        return par1 ** par2
    elif operation == '/' or operation == 'div':
        return par1 / par2
    elif operation == '//' or operation == 'int-div':
        return par1 // par2
    elif operation == '%' or operation == 'mod':
        return par1 % par2
    else:
        legalOperations = ['+ or add', '- or sub', '* or mul', '** or pow', '/ or div', '// or int-div', '% or mod']
        print('Function not defined or keyword has been specified! Please enter in one of the following operations: {}'. format(legalOperations))
            
print(calc('add', 10, 4))

14


<h3>10 - 09</h3>

In [25]:
def calculator(number1, number2):
    add = number1 + number2
    sub = number1 - number2
    mult = number1 * number2
    div = number1 / number2
    
    return add, sub, mult, div

add, sub, mult, div = calculator(9,3)
print(mult)

27


In [22]:
def unique_list(lst):
    new_lst = []
    for item in lst:
        if item not in new_lst:
            new_lst.append(item)
    return new_lst
            
lst = ['a', 'c', 'b', 'b', 'c', 'a', 'd']

print(unique_list(lst))

['a', 'c', 'b', 'd']


<h3>10 - 12</h3>

In [2]:
def isPalindrome(string):
    if string == string[::-1]:
        return True
    else:
        return False
string = "tacocat"
isPalindrome(string)

True

In [29]:
def isPalindrome(string):
    lchar = 0
    rchar = len(string) - 1
    index = 0
    for i in range(len(string)):
        if string[lchar] == string[rchar]:  
            rchar += 1
            lchar -= 1
            return True
        else: return False

pal = "tacocat"
# string2 = "nottacocat"

isPalindrome(pal)
# isPalindrome(string2)

True

In [33]:
def isPalindrome(string):
    pass
#     lchar = 0
#     rchar = len(string) - 1
#     while rchar >= lchar:
#         if not string[lchar] == string[rchar]:
#                return False
#         rchar += 1
#         lchar -= 1
#     return True
    
string = "tacocat"
# string2 = "nottacocat"

isPalindrome(string)
# isPalindrome(string2)

<h5>Libraries:</h5>
import random - generating random numbers
import os - interacting with siles in your computer
import re - sequence of character to create search pattern
import datetime - date and formating
import math - math functions
import xml - processing xml

NumPy = Numerical Python
core of NumPy is ndarray (n dimentional array): container of items of same type and size

In [3]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print(matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


lists whithin lists are easy to use but not efficient

In [4]:
import numpy

arr = numpy.array(matrix)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
# arr[row][column]
print(arr[1][1])

5


In [41]:
# arr[row,column]
print(arr[1,2])

6


<h3>10 - 14 </h3>

<a href = "https://numpy.org/doc/stable/reference/">NumPy</a> submodules:
.sin, .cos, .log, .exp, .max, .min

In [5]:
numpy.max(arr)

9

In [7]:
a = numpy.array([45, 2, 59, -2, 70, 3, 6, 790])
print("Minimun:", numpy.min(a))
print("Cosine of 0th element: {:.2f}".format(numpy.cos(a[0])))

Minimun: -2
Cosine of 0th elemnt: 0.53


Fourier transforms: <b><a href = "https://numpy.org/doc/stable/reference/routines.fft.html">.fft</a></b>
several applications, any continuous function can be produced as an infinite sum of sine and cosine waves. 

Linear algebr: <b><a href = "https://numpy.org/doc/stable/reference/routines.linalg.html">.linalg</a></b>
.linalg.norm - vector norms
.linalg.svd - singular value decomposition
.linalg.det - determinant

Random numbers: <b><a href = "https://numpy.org/doc/stable/reference/random/index.html">.random</a></b>
Can generate random arrays of data. 
Thread safe. Thread: multiple independent calls at the same time.

Testing: <b><a href = "https://numpy.org/doc/stable/reference/routines.testing.html">.testing.[error]</a></b>
Testing code for errors

In [10]:
our_list = [5, 10, 15, 20, 25]
new_list = []
for i in our_list:
    new_list.append(i ** 2)
print(new_list)

[25, 100, 225, 400, 625]


In [11]:
our_list = numpy.array(our_list)
our_list = our_list ** 2
print(our_list)

[ 25 100 225 400 625]


In [ ]:
new_list = [10, 21, 30, 43, 54]
new_list = numpy.array(new_list)
new_list = new_list // 5
print(new_list)

In [ ]:
# (slide 30 @ 43 min)
vector = [ 4.0, 15.0, 6.0, 2.0]
magnitude = 0.0
for element in vector:
    magnitude +- element ** 2
magnitude = (magnitude ** 0.5)
print("Original magnitude:", magnitude)

In [ ]:
new_magnitude = 0.0
for index in range(len(vector)):
    element = vector[index]
    vector[index] = element / magnitude
    new_magnitude += vector[index] ** 2
new_magnitude = (new_magnitude ** 0.5)
print("Normal magnitude:", new_magnitude)

In [2]:
import numpy as np
import numpy.linalg as nla

In [19]:
vector = [ 4.0, 15.0, 6.0, 2.0]

np_vector = np.array(vector)
magnitude = nla.norm(np_vector)
print("Original magnitude: {:.2f}".format(magnitude))

np_vector /= magnitude
new_magnitude = nla.norm(np_vector)
print("Normalized magnitude: {:.2f}".format(new_magnitude))

Original magnitude: 16.76
Normalized magnitude: 1.00


<h3>10 - 16</h3>

In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = x + y
print(z)

In [10]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A @ B #matrix multiplication

array([[19, 22],
       [43, 50]])

In [5]:
tensor = np.array([[1,2], [3,4], [5,6]])
print(tensor.shape)

(3, 2)


In [37]:
def multiply_loops(A,B):
    C = np.zeros((A.shape[0], B.shape[1]))
    for i in range(len(A)):       
        for j in range(len(B[0])):  
            for k in range(len(B)):
                C[i][j] += A[i][k] * B[k][j]
    return C
print(multiply_loops(A,B))

[[19. 22.]
 [43. 50.]]


In [25]:
import iLtimeit
X = np.random.random((100, 100))
Y = np.random.random((100, 100))

9.58 µs ± 2.73 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [26]:
def multiply_vectors(A,B):
    result = A @ B
    return result

91.4 µs ± 19.8 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [31]:
%timeit multiply_loops(X, Y)
%timeit multiply_vectors(X, Y)

50 ms ± 24.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
106 µs ± 48.9 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


List Indexing

In [44]:
li = ['this', 'is', 'a', 'list']
print(li)
print(li[1:3])
print(li[2:])
print(li[:-1])

['this', 'is', 'a', 'list']
['is', 'a']
['a', 'list']
['this', 'is', 'a']


In [50]:
x = np.array([1,2,3,4,5])
print(x)
print(x[1: 3])
print(x[2: ])
print(x[: -1])

[1 2 3 4 5]
[2 3]
[3 4 5]
[1 2 3 4]


In [48]:
python_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(python_matrix)
print(python_matrix[0])
print(python_matrix[0][0])

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[1, 2, 3]
1


In [49]:
numpy_matrix = np.array(python_matrix)
print(numpy_matrix)
print(numpy_matrix[0])
print(numpy_matrix[0][0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
1


array[row,colum]
indexes start at 0

In [51]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[:, 1])

[2 5 8]


<h5>.shape</h5>
len(narray.shape) = returns number of elements in the matrix

<h3>10 - 19</h3>

array[row,colum]<br>
indexes start at 0<br>
it's possible to use slicing to reference the arrays<br>
arr[:2, 1:] all rows up to - but not including - row 2 / all columns starting at - but not including - col 1<br>
arr[2] / arr[2, :], arr[2:,:]<br>
arr[:,:2]<br>
arr[1,:2]<br>
arr[1:2, :2]<br>

<b>Advanced Slicing:</b>
Simple slicing: [start:end]<br>
Advanced slicing: [started:end:step]<br><br>

<b>Numpy functions:</b>
.arange(a,b) - creates a range starting from a to b<br>
.reshape(a,b) - reshapes the array in a matris with a rows and b columns<br>
.empty(shape(x,y,z)) - returns new array with shape defined by user - x,y,z being the 3dimentions<br>
.ndim() - returns the number of dimentions in the array<br>
len(array.shape)) - also returns the number of dimentions in the array<br>
del array - deletes an array structure<br>
.size - returns the size of the array<br>
.zeros / .ones - creates an array with only zeros or ones<br>

In [8]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a[:,1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [22]:
import numpy as np
array_data = np.arange(0, 36).reshape(6,6)
print(array_data)

slicing = array_data[2::2, ::2]
print("\nEstracted data:\n", slicing)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

Estracted data:
 [[12 14 16]
 [24 26 28]]


<b>5 Axis Numpy object:</b><br>
Axis 0 = color<br>
Axis 1 = height<br>
Axis 2 = width<br>
Axis 3 = depth<br>
Axis 4 = frame

In [24]:
tensor = np.empty(shape = (2,640,480,360,100))
print(tensor.shape)
print(tensor.size)
del tensor

(2, 640, 480, 360, 100)
22118400000


In [29]:
example = np.zeros(shape = (3,5,9))
print(example.shape)
print(example)
sliced = example[0]
print(sliced.shape)
print(sliced)
double_sliced = example[0,0]
print(double_sliced.shape)
print(double_sliced)

(3, 5, 9)
[[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]]]
(5, 9)
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(9,)
[0. 0. 0. 0. 0. 0. 0. 0. 0.]


<h2>RESEARCH: <b>List Comprehension and Broadcasting</b></h2>
Perform an operation on the entire array. Arrays need to be compatible.


<h3>10 - 26</h3>

filesystem interaction / user input

In [1]:
name = input("Enter your name: ")
print(type(name))

Enter your name:  Barbara


<class 'str'>


In [2]:
age = int(input("Enter your age: "))
print(type(age))

Enter your age:  23


<class 'int'>


In [3]:
file_object = open("files/alice.txt", 'r')
contents = file_object.read()
print(contents[:71])
file_object.close()

Project Gutenberg's Alice's Adventures in Wonderland, by Lewis Carroll



In [35]:
with open("files/alice.txt", 'r') as alice_f:
    contents = alice_f.read()
    print(contents[597:12140])

ALICE'S ADVENTURES IN WONDERLAND

Lewis Carroll

THE MILLENNIUM FULCRUM EDITION 3.0




CHAPTER I. Down the Rabbit-Hole

Alice was beginning to get very tired of sitting by her sister on the
bank, and of having nothing to do: once or twice she had peeped into the
book her sister was reading, but it had no pictures or conversations in
it, 'and what is the use of a book,' thought Alice 'without pictures or
conversations?'

So she was considering in her own mind (as well as she could, for the
hot day made her feel very sleepy and stupid), whether the pleasure
of making a daisy-chain would be worth the trouble of getting up and
picking the daisies, when suddenly a White Rabbit with pink eyes ran
close by her.

There was nothing so VERY remarkable in that; nor did Alice think it so
VERY much out of the way to hear the Rabbit say to itself, 'Oh dear!
Oh dear! I shall be late!' (when she thought it over afterwards, it
occurred to her that she ought to have wondered at this, but at the time
it

In [42]:
with open("files/alice.txt", 'r') as file_object:
    lines_of_text = file_object.readline()
    print(lines_of_text)

Project Gutenberg's Alice's Adventures in Wonderland, by Lewis Carroll



In [ ]:
with open("files/alice.txt", 'r') as file_object:
    lines_of_text = file_object.readlines()
    print(lines_of_text[8])

In [12]:
data_to_save = "LINE OF CODE 2\n"
file_object = open("files/outfile.txt", 'w')
file_object.write(data_to_save)
file_object.close()

.write() overwritte previous file content

In [13]:
with open("outfile.txt", 'w') as alice_f:
    alice_f.write(data_to_save)

<h3>10 - 28</h3>

Solution to Question 3 fom midterm exam

In [1]:
def decode(s):
    decoded_list = []
#     decoded = "" 
    index = 0
    
    while index < len(s):
        count = int(s[index])
        index += count
        decoded_list.append(s[index+1])
#         decoded += (s[index+1])
        
        index += 2
        decoded = "".join(decode_list)
        
    return decoded

<h4>>> Appending to an existing file<h4>

In [14]:
data_to_save = "Data being appended\n"
with open("files/outfile.txt", 'a') as file_object:
    file_object.write(data_to_save)

In [16]:
with open("files/outfile.txt", 'r') as file_object:
    for i in range(3):
        print(file_object.readline().strip())

LINE OF CODE 2
Data being appended



<h3>10 - 30</h3>

Relative path = a file in a directory
Absolute path = full address of a file in the OS

os library - imports miscellaneous operating system interfaces
os.getcwd() - gets file/folder path
os.chdir('path to change to') - moves to another folder
os.listdir() - list all files in folder
os.mkdir('folder path and name') - creates a directory
os.rmdif('folder path and name') - removes a directory
os.unlink('file path and name') - removes a file
os.remove('file path and name') - removes a file
os.rename('current name', 'new name') - renames files or folders
os.path - module from os library
    .exists(), 
    .lexists(), 
    .isdir(), 
    .isfile(), 
    .islink(),
    .ismount()
    .join()

In [4]:
import os # 
os.getcwd() # gets file path

'/Users/barbararocha/Google Drive - CofC/DATA_101'

In [13]:
os.chdir('..') #changes directories
print(os.getcwd())
os.chdir('DATA_101')
print(os.getcwd())

/Users/barbararocha/Google Drive - CofC


'/Users/barbararocha/Google Drive - CofC/DATA_101'

In [14]:
os.listdir()

['HW02.ipynb',
 'lists.py',
 '.DS_Store',
 'W06 - Conditionals - if, elif, else.html',
 'HW01.ipynb',
 'W09 - Array indexing, slicing and broadcasting.html',
 'W04 - Lists, Dictionaries and Loops.html',
 'Polygon.py',
 'HW03.ipynb',
 'outfile.txt',
 'HW03.pdf',
 'W01 - Data Science introduction.html',
 'HW02.pdf',
 'Practice_Examples.ipynb',
 'HW01.pdf',
 'W08 - Numpy, Vectors and vector operations.html',
 'Fall_2020_DATA_101_Syllabus.pdf',
 'practice.ipynb',
 'W07 - Error handling, Functions.html',
 'files',
 'Elsevier-SDG-Report-2020.pdf',
 '.ipynb_checkpoints',
 'W05 - List comprehension, Nested loops - format, range, zip, enumerate.html',
 'W02 - Python introduction - operators.html',
 'Notes.ipynb',
 '.idea',
 'W03 - Variables, Strings, Comments and Spaces.html']

In [16]:
import os
print(os.listdir())
path = '/Users/barbararocha/Google Drive - CofC/DATA_101/new_folder_nam'
os.mkdir(path)
print(os.listdir())

['HW02.ipynb', 'lists.py', '.DS_Store', 'W06 - Conditionals - if, elif, else.html', 'HW01.ipynb', 'W09 - Array indexing, slicing and broadcasting.html', 'W04 - Lists, Dictionaries and Loops.html', 'Polygon.py', 'HW03.ipynb', 'outfile.txt', 'HW03.pdf', 'W01 - Data Science introduction.html', 'HW02.pdf', 'Practice_Examples.ipynb', 'HW01.pdf', 'W08 - Numpy, Vectors and vector operations.html', 'Fall_2020_DATA_101_Syllabus.pdf', 'practice.ipynb', 'W07 - Error handling, Functions.html', 'files', 'Elsevier-SDG-Report-2020.pdf', '.ipynb_checkpoints', 'W05 - List comprehension, Nested loops - format, range, zip, enumerate.html', 'W02 - Python introduction - operators.html', 'Notes.ipynb', '.idea', 'W03 - Variables, Strings, Comments and Spaces.html']
['HW02.ipynb', 'lists.py', '.DS_Store', 'new_folder_nam', 'W06 - Conditionals - if, elif, else.html', 'HW01.ipynb', 'W09 - Array indexing, slicing and broadcasting.html', 'W04 - Lists, Dictionaries and Loops.html', 'Polygon.py', 'HW03.ipynb', 'out

In [17]:
print(os.listdir())
os.rmdir(path)
print(os.listdir())

['HW02.ipynb', 'lists.py', '.DS_Store', 'new_folder_nam', 'W06 - Conditionals - if, elif, else.html', 'HW01.ipynb', 'W09 - Array indexing, slicing and broadcasting.html', 'W04 - Lists, Dictionaries and Loops.html', 'Polygon.py', 'HW03.ipynb', 'outfile.txt', 'HW03.pdf', 'W01 - Data Science introduction.html', 'HW02.pdf', 'Practice_Examples.ipynb', 'HW01.pdf', 'W08 - Numpy, Vectors and vector operations.html', 'Fall_2020_DATA_101_Syllabus.pdf', 'practice.ipynb', 'W07 - Error handling, Functions.html', 'files', 'Elsevier-SDG-Report-2020.pdf', '.ipynb_checkpoints', 'W05 - List comprehension, Nested loops - format, range, zip, enumerate.html', 'W02 - Python introduction - operators.html', 'Notes.ipynb', '.idea', 'W03 - Variables, Strings, Comments and Spaces.html']
['HW02.ipynb', 'lists.py', '.DS_Store', 'W06 - Conditionals - if, elif, else.html', 'HW01.ipynb', 'W09 - Array indexing, slicing and broadcasting.html', 'W04 - Lists, Dictionaries and Loops.html', 'Polygon.py', 'HW03.ipynb', 'out

In [20]:
import os
for file in os.listdir(os.getcwd()):
    if file.endswith('.txt'):
        print(os.path.join(os.getcwd(),file))


/Users/barbararocha/Google Drive - CofC/DATA_101/outfile.txt


<h4> VECTORS </h4>

vector magnitude - lenght(number os elements)

vector direction - 


In [24]:
import numpy as np
# array = np.array[5,5]